[project]
name = "gndless_sample_rate_conversion"
version = "0.4.0"
authors = ["Akiyuki Okayasu"]
description = "Synchronous and asynchronous sample-rate converters for Veryl."
license = "MIT OR Apache-2.0"
repository = "https://github.com/AkiyukiOkayasu/gndless-sample-rate-conversion-veryl"

[build]
sources = ["src"]
clock_type = "posedge"
reset_type = "sync_high"
target = { type = "directory", path = "target" }

[test]

[dependencies]
gndless_fixedpoint = { github = "AkiyukiOkayasu/gndless-fixedpoint-veryl", version = "0.2.2" }
gndless_interpolation = { github = "AkiyukiOkayasu/gndless-interpolation-veryl", version = "0.3.0" }
gndless_nco = { github = "AkiyukiOkayasu/gndless-nco-veryl", version = "0.2.0" }

[publish]
register = true
bump_commit = true
publish_commit = true
