name: CI

on:
  push:
    branches: ['main', 'dev']
  pull_request:
    branches: ['main']
    types: [opened, synchronize, reopened]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: veryl-lang/setup-veryl@v1
        with:
          version: nightly
      - name: Format check
        continue-on-error: true
        run: veryl fmt --check
      - run: veryl check
      - run: veryl build
      - run: veryl test
      - run: veryl doc

  backend-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: veryl-lang/setup-veryl@v1
        with:
          version: nightly
      - run: veryl test --backend-validate
